services:
    front:
        #network_mode: "host"
        container_name: front_container
        environment: 
            - BACKEND_URL=http://back:3000
        build: ./frontend
        ports:
            - "9080:80"
        networks:
            - container_connection
    back:
        #network_mode: "host"
        container_name: back_container
        environment: 
            - API_URL=http://api:5000
            - FRONTEND_URL=http://front:80
        build: ./backend
        ports:
            - "3002:3000"
        networks:
            - container_connection
    api:
        #network_mode: "host"
        container_name: api_container
        build: ./api
        ports:
            - "5000:5000"
        networks:
            - container_connection

networks:
    container_connection : 
        driver: bridge
