
version: "2.0"
services: 
  api: 
    build: ./api
    container_name: api_container
    environment: 
        - BACKEND_URL=http://192.168.1.35:3002
    ports: 
      - "5000:5000"
    networks:
        - container_connection
  back: 
    build: ./backend
    container_name: back_container
    environment: 
        - API_URL=http://api:5000
        - FRONTEND_URL=http://192.168.1.35:9080
    ports: 
      - "3002:3000"
    networks:
        - container_connection
  front: 
    build: ./frontend
    container_name: front_container
    ports: 
      - "9080:80"
    networks:
        - container_connection
        
  node_exporter: 
    container_name: node-exporter
    image: prom/node-exporter
    pid: host
    ports: 
      - "9100:9100"
    restart: always
  prometheus: 
    build: ./prometheus
    container_name: prometheus
    ports: 
      - "9090:9090"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - api_container

  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - 9000:3000
    #volumes:
      #- grafana-data:/var/lib/grafana

networks:
    container_connection : 
        driver: bridge