services:
    front:
        network_mode: "host"
        container_name: front_container
        environment: 
            - BACKEND_URL=http://localhost:3002
        build: ./frontend
        ports:
            - "9080:80"
    back:
        network_mode: "host"
        container_name: back_container
        environment: 
            - API_URL=http://api:5000
            - FRONTEND_URL=http://localhost:9080
        build: ./backend
        ports:
            - "3002:3000"
    api:
        network_mode: "host"
        container_name: api_container
        build: ./api
        ports:
            - "5000:5000"
