services:
    front:
        container_name: front_container_maud_jen
        environment: 
            - BACKEND_URL=http://192.168.1.35:3002
        build: ./frontend
        ports:
            - "9080:80"
        networks:
            - container_connection
    back:
        container_name: back_container_maud_jen
        environment: 
            - API_URL=http://api:5000
            - FRONTEND_URL=http://192.168.1.35:9080
        build: ./backend
        ports:
            - "3002:3000"
        networks:
            - container_connection
    api:
        container_name: api_container_maud_jen
        build: ./api
        ports:
            - "5000:5000"
        networks:
            - container_connection
networks:
    container_connection : 
        driver: bridge
