global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml

scrape_configs:
  - job_name: node
    static_configs:
      - targets: 
        - 'node-exporter:9100'
  #- job_name: front
    #static_configs:
      #- targets: 
        #- 'front_container:80'
  - job_name: back
    static_configs:
      - targets: 
        - 'back_container:3002'
  - job_name: api
    static_configs:
      - targets: 
        - 'api_container:5000'
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
