global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml

scrape_configs:
  - job_name: node
    static_configs:
      - targets: 
        - 'node-exporter:9100'
  - job_name: front
    static_configs:
      - targets: 
        - 'localhost:80'
  - job_name: back
    static_configs:
      - targets: 
        - 'back_container:3000'
  - job_name: api
    static_configs:
      - targets: 
        - 'api_container:8010'
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
